version: '3'

services:
  app:
    build: .
    container_name: codeflix-videos-app
    volumes:
      - .:/home/node/app
      - ~/.ssh:/root/.ssh
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock